baseURL = 'https://andrew.molyuk.com/'
canonicalURL = 'https://andrew.molyuk.com/'
languageCode = 'ru'
title = '#andrewmolyuk'
license = 'MIT'

enableRobotsTXT = true
enableSitemapXML = true

[author]
	name = 'Andrew Molyuk'
	email = 'andrew@molyuk.com'

[params]
	description = 'Мой персональный сайт с блогом, где я пишу о технических и не только темах, open-source проектах, а также делюсь советами и новостями.'
	keywords = 'Технологии,Программирование,Электроника,Личное развитие,Продуктивность,Блог,Статьи,Руководства,Советы'

[taxonomies]
	tag = 'blog/tags'

[outputs]
	page = ['HTML']
	home = ['HTML']
	section = ['HTML', 'RSS']
	taxonomy = ['HTML']
	term = ['HTML']

[outputFormats]
	[outputFormats.RSS]
		mediatype = "application/rss"
		baseName = "rss"
