baseURL = 'https://andrew.molyuk.com/'
title = '#andrewmolyuk'
enableRobotsTXT = true
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[author]
    name = 'Andrew Molyuk'

[menu]
    [[menu.main]]
        name = "Info"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Works"
        url = "/works/"
        weight = 2
    [[menu.main]]
        name = "Links"
        url = "/links/"
        weight = 3
    [[menu.main]]
        name = "Блог"
        url = "/blog/"
        weight = 4

[taxonomies]
    tag = "tags"

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"