baseURL = 'https://andrew.molyuk.com/'
canonicalURL = 'https://andrew.molyuk.com/'
languageCode = 'ru'
title = '#andrewmolyuk'
license = 'MIT'

enableRobotsTXT = true
enableSitemapXML = true
googleAnalytics = 'G-J9DSCZ2KKH'

[author]
	name = 'Andrew Molyuk'
	email = 'andrew@molyuk.com'

[params]
	description = 'Personal website of Andrew Molyuk where I write about programming, web development, and other stuff.'
	keywords = 'andrew molyuk, personal website, blog, open-source projects'

[services.rss]
  limit = 10

[taxonomies]
	tag = 'blog/tags'

[outputs]
	page = ['HTML']
	home = ['HTML']
	section = ['HTML', 'RSS']
	taxonomy = ['HTML']
	term = ['HTML']

[outputFormats]
	[outputFormats.RSS]
		mediatype = "application/rss"
		baseName = "rss"
