baseURL = 'https://andrew.molyuk.com/'
title = '#andrewmolyuk'
description = 'Andrew and his scribbles'
images = ['/img/jumbo.jpeg']
enableRobotsTXT = true
copyright = 'This work is licensed under a MIT License.'
googleAnalytics = 'UA-2324643-1'

[author]
    name = 'Andrew Molyuk'

[menu]
    [[menu.main]]
        name = "Info"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Links"
        url = "/links/"
        weight = 2
    [[menu.main]]
        name = "Блог"
        url = "/blog/"
        weight = 3

[taxonomies]
    tag = "tags"

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"