baseURL = 'https://andrew.molyuk.com/'
canonicalURL = 'https://andrew.molyuk.com/'
title = "#andrewmolyuk"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "G-J9DSCZ2KKH"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true 

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "solarized-dark"

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "ru"

[params.info]
  description = "All about that programming, web, and other stuff."
  title404 = "Nothing's here!"

[params.assets]
  favicon = "images/favicon.svg"
  gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
  prefix = ""
  holder = "Andrew Molyuk"
  startYear = "2018"
  suffix = ""

[params.settings]
  # date & time format: https://golang.org/pkg/time/
  dateFormat = "2 Jan 2006"
  listDateFormat = "2 Jan 2006"
  archiveDateFormat = "2 Jan"
  hideEntryNavigation = ["page"] # boolean / array of sections
  hideEntryMeta = ["page"]       # boolean / array of sections
  showReadingTime = true
  showLastmod = true
  taxonomyCloudShuffle = true
  accentColor = "#ffcd00"
  hideMainMenu = true

[params.sidebar]
  enable = true

[params.widgets]
  header = []
  homepage = ["recent_posts"]
  sidebar = ["about","search","taxonomy_cloud"]
  footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.social]
  email = "andrew@molyuk.com"
  facebook = "andrew.molyuk"
  github = "andrewmolyuk"
  linkedin = "andrewmolyuk"
  telegram = "andrewmolyuk"

[params.comments]
  enable = true

# Utterances: https://utteranc.es
[params.comments.utterances]
  enable = true
  issueTerm = "pathname" # pathname / url / title / og:title / <string>
  label = ""
  theme = "github-light"

[params.comments.utterances.github]
  username = "andrewmolyuk"
  repository = "andrew.molyuk.com"

[params.search]
  client = "fuse"

[taxonomies]
  tag = "tags"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Repo"
  weight = -10
  identifier = "repository"
  url = "https://github.com/andrewmolyuk/andrew.molyuk.com"

[blackfriday]
  hrefTargetBlank = true

[languages]
# edit this block for your own language
  [languages.ru]
    lang = "ru"
    languageName = "Russian"
    weight = 1

[services.rss]
  limit = 10
  