[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    locale = "ru"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.1

  [[plugins.inputs.audits]]
    path = "index.html"

  [[plugins.inputs.audits]]
    path = "blog/index.html"

  [[plugins.inputs.audits]]
    path = "projects/index.html"

  [[plugins.inputs.audits]]
    path = "blog/tags/hugo/index.html"

  [[plugins.inputs.audits]]
    path = "blog/howto-deploy-hugo-to-netlify/index.html"
